add_compile_options(-w)

set(BUILD_ONLY "s3" CACHE STRING "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(AUTORUN_UNIT_TESTS OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(CMAKE_WARN_DEPRECATED FALSE)

add_subdirectory(../aws-sdk-cpp ${CMAKE_CURRENT_BINARY_DIR}/aws-sdk-cpp)
